### ISSUE TITLE
Not working with python 3.5

### ISSUE THREAD

**Issue by ToLi91** [dw/alembic-autogenerate-enums#2]
`Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.5/dist-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 117, in revision
    script_directory.run_env()
  File "/usr/local/lib/python3.5/dist-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.5/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.5/dist-packages/alembic/util/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./alembic/env.py", line 146, in <module>
    run_migrations_online()
  File "./alembic/env.py", line 127, in run_migrations_online
    context.run_migrations(engine_name=rec['type'])
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.5/dist-packages/alembic/runtime/migration.py", line 303, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/usr/local/lib/python3.5/dist-packages/alembic/command.py", line 97, in retrieve_migrations
    revision_context.run_autogenerate(rev, context)
  File "/usr/local/lib/python3.5/dist-packages/alembic/autogenerate/api.py", line 369, in run_autogenerate
    self._run_environment(rev, migration_context, True)
  File "/usr/local/lib/python3.5/dist-packages/alembic/autogenerate/api.py", line 405, in _run_environment
    autogen_context, migration_script)
  File "/usr/local/lib/python3.5/dist-packages/alembic/autogenerate/compare.py", line 22, in _populate_migration_script
    _produce_net_changes(autogen_context, upgrade_ops)
  File "/usr/local/lib/python3.5/dist-packages/alembic/autogenerate/compare.py", line 48, in _produce_net_changes
    autogen_context, upgrade_ops, schemas
  File "/usr/local/lib/python3.5/dist-packages/alembic/util/langhelpers.py", line 314, in go
    fn(*arg, **kw)
  File "/usr/local/lib/python3.5/dist-packages/alembic_autogenerate_enums.py", line 124, in compare_enums
    declared = get_declared_enums(autogen_context.metadata, schema, default)
  File "/usr/local/lib/python3.5/dist-packages/alembic_autogenerate_enums.py", line 63, in get_declared_enums
    for table in metadata.tables.itervalues()
AttributeError: 'immutabledict' object has no attribute 'itervalues'`

If you change itervalues() on row 63 to values()
and iteritems() on row 148 to items()
then it works on 3.5

**Comment by dw** [comment]
Thank you. If you can, submit a pull request :) Otherwise I will fix when I have free time.

**Comment by ToLi91** [comment]
Now there is a pull request :)

**Comment by dw** [comment]
Thanks!
